train_path: path/to/dataset
test_path: path/to/dataset

outdir: path/to/output_dir

train_batch_size: 16    
bert_hidden_dim: 768   
electra_hidden_dim: 503
valid_batch_size: 16  
max_len: 250

forget_rate: 0.2
agreement_threshold: 1

max_model_save: 5

eval_step: 1
evi_num: 8

src_flag: False
hyp_flag: False

bert_pretrain: path/to/pre_trained_model

model_name: bert

learning_rate: 0.0001
num_train_epochs: 100
gradient_accumulation_steps: 8 

cuda : True

wandb_key: wandb_key
wandb_proj_name: Project_name
wandb_run_name: Run_name
